// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1KJtgOdo8gPx_fDZ_bTcbr5VvcUxA7k',
    appId: '1:565447947765:android:057d688ea320aa0be21cbc',
    messagingSenderId: '565447947765',
    projectId: 'innovator-250f8',
    storageBucket: 'innovator-250f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqNMc6i3rSUmWCA-gyvRic2gtC3Kkcc4s',
    appId: '1:565447947765:ios:8e8717f98ce98ad0e21cbc',
    messagingSenderId: '565447947765',
    projectId: 'innovator-250f8',
    storageBucket: 'innovator-250f8.firebasestorage.app',
    androidClientId: '565447947765-h47b71t7lomlihrc5mfahutdoj214lrs.apps.googleusercontent.com',
    iosClientId: '565447947765-pf1nqtcdcpv9k5sbm0c41854l66i8cm6.apps.googleusercontent.com',
    iosBundleId: 'com.innovation.innovator',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiNJHXlMnf3ZFf0x9xFkVT6lHnIzYgR98',
    appId: '1:565447947765:web:6b45f84cb0202ec6e21cbc',
    messagingSenderId: '565447947765',
    projectId: 'innovator-250f8',
    authDomain: 'innovator-250f8.firebaseapp.com',
    storageBucket: 'innovator-250f8.firebasestorage.app',
    measurementId: 'G-BRETG8JVF5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqNMc6i3rSUmWCA-gyvRic2gtC3Kkcc4s',
    appId: '1:565447947765:ios:8e8717f98ce98ad0e21cbc',
    messagingSenderId: '565447947765',
    projectId: 'innovator-250f8',
    storageBucket: 'innovator-250f8.firebasestorage.app',
    androidClientId: '565447947765-h47b71t7lomlihrc5mfahutdoj214lrs.apps.googleusercontent.com',
    iosClientId: '565447947765-pf1nqtcdcpv9k5sbm0c41854l66i8cm6.apps.googleusercontent.com',
    iosBundleId: 'com.innovation.innovator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiNJHXlMnf3ZFf0x9xFkVT6lHnIzYgR98',
    appId: '1:565447947765:web:d5a32071120d346ce21cbc',
    messagingSenderId: '565447947765',
    projectId: 'innovator-250f8',
    authDomain: 'innovator-250f8.firebaseapp.com',
    storageBucket: 'innovator-250f8.firebasestorage.app',
    measurementId: 'G-CMKXLS88GR',
  );

}